apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: contour-my-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: contour-my-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-Secret: contour-my-packages-values
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: contour-my-packages-sa
    kapp.k14s.io/change-rule: "delete before deleting serviceaccount"
  name: contour
  namespace: my-packages
spec:
  serviceAccountName: contour-my-packages-sa
  packageRef:
    refName: contour.tanzu.vmware.com
    versionSelection:
      constraints: 1.18.2+vmware.1-tkg.1
  values:
  - secretRef:
      name: contour-my-packages-values
---
apiVersion: v1
data:
  contour-value.yaml: LS0tCmluZnJhc3RydWN0dXJlX3Byb3ZpZGVyOiB2c3BoZXJlCm5hbWVzcGFjZTogdGFuenUtc3lzdGVtLWluZ3Jlc3MKY29udG91cjoKIGNvbmZpZ0ZpbGVDb250ZW50czoge30KIHVzZVByb3h5UHJvdG9jb2w6IGZhbHNlCiByZXBsaWNhczogMgogcHNwTmFtZXM6ICJ2bXdhcmUtc3lzdGVtLXJlc3RyaWN0ZWQiCiBsb2dMZXZlbDogaW5mbwplbnZveToKIHNlcnZpY2U6CiAgIHR5cGU6IExvYWRCYWxhbmNlcgogICBhbm5vdGF0aW9uczoge30KICAgbm9kZVBvcnRzOgogICAgIGh0dHA6IG51bGwKICAgICBodHRwczogbnVsbAogICBleHRlcm5hbFRyYWZmaWNQb2xpY3k6IENsdXN0ZXIKICAgZGlzYWJsZVdhaXQ6IGZhbHNlCiBob3N0UG9ydHM6CiAgIGVuYWJsZTogdHJ1ZQogICBodHRwOiA4MAogICBodHRwczogNDQzCiBob3N0TmV0d29yazogZmFsc2UKIHRlcm1pbmF0aW9uR3JhY2VQZXJpb2RTZWNvbmRzOiAzMDAKIGxvZ0xldmVsOiBpbmZvCiBwc3BOYW1lczogbnVsbApjZXJ0aWZpY2F0ZXM6CiBkdXJhdGlvbjogODc2MGgKIHJlbmV3QmVmb3JlOiAzNjBo
kind: Secret
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: contour-my-packages
    kapp.k14s.io/change-group: serviceaccount
  name: contour-my-packages-values
  namespace: my-packages
type: Opaque
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: contour-my-packages
    kapp.k14s.io/change-group: serviceaccount
  name: contour-my-packages-sa
  namespace: my-packages
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: contour-my-packages
    kapp.k14s.io/change-group: serviceaccount
  name: contour-my-packages-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: contour-my-packages
    kapp.k14s.io/change-group: serviceaccount
  name: contour-my-packages-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: contour-my-packages-cluster-role
subjects:
- kind: ServiceAccount
  name: contour-my-packages-sa
  namespace: my-packages

# contour-value.yaml
# ---
# infrastructure_provider: vsphere
# namespace: tanzu-system-ingress
# contour:
#  configFileContents: {}
#  useProxyProtocol: false
#  replicas: 2
#  pspNames: "vmware-system-restricted"
#  logLevel: info
# envoy:
#  service:
#    type: LoadBalancer
#    annotations: {}
#    nodePorts:
#      http: null
#      https: null
#    externalTrafficPolicy: Cluster
#    disableWait: false
#  hostPorts:
#    enable: true
#    http: 80
#    https: 443
#  hostNetwork: false
#  terminationGracePeriodSeconds: 300
#  logLevel: info
#  pspNames: null
# certificates:
#  duration: 8760h
#  renewBefore: 360h
