apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: cert-manager-my-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: cert-manager-my-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: cert-manager-my-packages-sa
  name: cert-manager
  namespace: my-packages
spec:
  serviceAccountName: cert-manager-my-packages-sa
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: 1.5.3+vmware.2-tkg.1
