apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package-ClusterRole: cert-manager-my-packages-cluster-role
    tkg.tanzu.vmware.com/tanzu-package-ClusterRoleBinding: cert-manager-my-packages-cluster-rolebinding
    tkg.tanzu.vmware.com/tanzu-package-ServiceAccount: cert-manager-my-packages-sa
    kapp.k14s.io/change-rule.req: "delete before deleting cert-manager-requirement"
    kapp.k14s.io/change-group.app: cert-manager
  name: cert-manager
  namespace: my-packages
spec:
  serviceAccountName: cert-manager-my-packages-sa
  packageRef:
    refName: cert-manager.tanzu.vmware.com
    versionSelection:
      constraints: 1.5.3+vmware.2-tkg.1
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cert-manager-my-packages
    kapp.k14s.io/change-group.req: cert-manager-requirement
    kapp.k14s.io/change-group.app: cert-manager
  name: cert-manager-my-packages-sa
  namespace: my-packages
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cert-manager-my-packages
    kapp.k14s.io/change-group.req: cert-manager-requirement
    kapp.k14s.io/change-group.app: cert-manager
  name: cert-manager-my-packages-cluster-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    tkg.tanzu.vmware.com/tanzu-package: cert-manager-my-packages
    kapp.k14s.io/change-group.req: cert-manager-requirement
    kapp.k14s.io/change-group.app: cert-manager
  name: cert-manager-my-packages-cluster-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cert-manager-my-packages-cluster-role
subjects:
- kind: ServiceAccount
  name: cert-manager-my-packages-sa
  namespace: my-packages
